version: 2

machine:
  environment:
    AWS_AMI_ID: ami-29160d47
    AWS_INSTANCE_TYPE: t2.micro
    AWS_CF_STACK_NAME: ci-test
    SSH_USER: ec2-user
    BASE_STACK_NAME: eks-dev-base

jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install the AWS CLI
          command: |
            echo $BASE_STACK_NAME
