version: 2

jobs:
  build:

    docker:
      - image: circleci/python:3.6.1

    environment:
      - AWS_AMI_ID: ami-29160d47
      - AWS_INSTANCE_TYPE: t2.micro
      - AWS_CF_STACK_NAME: ci-test
      - SSH_USER: ec2-user
      - BASE_STACK_NAME: eks-dev-base

    steps:
      - checkout
      - run:
          name: install the AWS CLI
          command: |
            sudo pip install --upgrade pip
            sudo pip install awscli
      - run:
          name: install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.9/2019-03-27/bin/linux/amd64/kubectl
            chmod +x kubectl
      - run:
          name: install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/darwin/amd64/aws-iam-authenticator
            chmod +x aws-iam-authenticator
      - run:
          name: create vpc
          command: |
            aws cloudformation create-stack --region ap-northeast-1 --stack-name ${BASE_STACK_NAME} --template-body=file://template-eks-base.yaml --capabilities CAPABILITY_NAMED_IAM
