# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  two:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: echo "A second hello"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
