version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install the AWS CLI
          command: |
            sudo pip install --upgrade pip
            sudo pip install awscli
      - run:
          name: install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.9/2019-03-27/bin/linux/amd64/kubectl
            chmod +x kubectl
      - run:
          name: install aws-iam-authenticator
          command: |
            curl -o ~/bin/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/darwin/amd64/aws-iam-authenticator
            chmod +x aws-iam-authenticator
