# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install the AWS CLI
          command: |
            sudo pip install --upgrade pip
            sudo pip install awscli --upgrade --user
            aws --version
